import argparse
import dotenv
import os
import pandas as pd
import sys

try:
    dotenv.load_dotenv(".env")
except ImportError as e:
    print(f"Error importing .env: {e}")
    sys.exit(1)

# Create an ArgumentParser object
parser = argparse.ArgumentParser()
parser.add_argument('filelist', type=str, help="Path to the file containing the sentences generated by gpt")
parser.add_argument('module_path', type=str, help="Path to the directory containing the utility module")
parser.add_argument('outdir', type=str, help="Path to the output directory")

# Parse command-line arguments
args = parser.parse_args()

# Add the specified path to sys.path
sys.path.append(args.module_path)

# Import the utility functions module
try:
    from utility_openai import get_embedding
except ImportError as e:
    print(f"Error importing module: {e}")
    sys.exit(1)

with open(args.filelist, 'r') as file:
    list_of_files = file.readlines()

list_of_new_files = []
for df_file in list_of_files:
    df_file = df_file.strip()
    df = pd.read_csv(df_file, compression='gzip')
    df['text-embedding-3-small'] = df['sentence'].apply(lambda x: get_embedding(x))
    filename = os.path.basename(df_file).split(".")[0]
    fileout = f"{filename}_embed-3.csv.gz"
    fileout_path = os.path.join(args.outdir, fileout)
    list_of_new_files.append(fileout_path)
    df.to_csv(fileout_path, compression="gzip", index=False)

# save the list of files
list_of_files_path = os.path.join(args.outdir, "list_of_files.txt")
with open(list_of_files_path, "w") as file:
    for item in list_of_new_files:
        file.write(item + "\n")

